### ISSUE TITLE
How I can run this code?

### ISSUE THREAD

**Issue by Alessandro-Stuccio** [swlkr/allyourpasswords#7]
i'can't run this code because xcode gives me some errors with SQLite.

**Comment by swlkr** [comment]
hmm could be a problem with the version of sqlite, might need an update

**Comment by Alessandro-Stuccio** [comment]
i don't know if i have to install sqlite or it's all in your files. thanks if you answer me

**Comment by swlkr** [comment]
oh you know what i think it depends on the system sqlite

**Comment by Alessandro-Stuccio** [comment]
is there any way to fix it?

**Comment by swlkr** [comment]
i think if you install sqlite it should work?

**Comment by Alessandro-Stuccio** [comment]
do i need to replace the files?

**Comment by swlkr** [comment]
This isn't related to sqlite at all, the fix is here: https://github.com/stephencelis/SQLite.swift/pull/1006/files

**Comment by Alessandro-Stuccio** [comment]
gives me another problem: Redefinition of 'sqlite3_file'

**Comment by swlkr** [comment]
You have to change this in the sqlite bridge objc file `@import SQLCipher.sqlite3;`

**Comment by Alessandro-Stuccio** [comment]
it did everything but gives me another problem: Thread 1: signal SIGABRT

**Comment by swlkr** [comment]
Hmm that's a tough one, here's what I did:

1. Clone repo
2. Change these two lines here

```diff
diff --git a/Pods/SQLite.swift/Sources/SQLite/Core/Connection.swift b/Pods/SQLite.swift/Sources/SQLite/Core/Connection.swift
index 1bbf7f7..189f511 100644
--- a/Pods/SQLite.swift/Sources/SQLite/Core/Connection.swift
+++ b/Pods/SQLite.swift/Sources/SQLite/Core/Connection.swift
@@ -587,7 +587,7 @@ public final class Connection {
         var flags = SQLITE_UTF8
         #if !os(Linux)
         if deterministic {
-            flags |= SQLITE_DETERMINISTIC
+            flags |= SQLite.SQLITE_DETERMINISTIC
         }
         #endif
         sqlite3_create_function_v2(handle, function, Int32(argc), flags, unsafeBitCast(box, to: UnsafeMutableRawPointer.self), { context, argc, value in
diff --git a/Pods/SQLite.swift/Sources/SQLiteObjc/include/SQLite-Bridging.h b/Pods/SQLite.swift/Sources/SQLiteObjc/include/SQLite-Bridging.h
index f8c2a3b..1a3f7ee 100644
--- a/Pods/SQLite.swift/Sources/SQLiteObjc/include/SQLite-Bridging.h
+++ b/Pods/SQLite.swift/Sources/SQLiteObjc/include/SQLite-Bridging.h
@@ -23,7 +23,7 @@
 //
 
 @import Foundation;
-@import SQLite3;
+@import SQLCipher.sqlite3;
 
 NS_ASSUME_NONNULL_BEGIN
 typedef NSString * _Nullable (^_SQLiteTokenizerNextCallback)(const char *input, int *inputOffset, int *inputLength);
```
3. Open `allyourpasswords.xcworkspace` in xcode
4. Change the active scheme to `allyourpasswords > Mac`
5. Hit run 
6. ✨ Worked!

Oh you know what, it asked me for permission to access the keychain and then after I gave that permission (with my mac password) it ran

**Comment by Alessandro-Stuccio** [comment]
<img width="1145" alt="Schermata 2021-04-03 alle 00 50 32" src="https://user-images.githubusercontent.com/81766448/113459730-a8603200-9416-11eb-9298-112c9c35b02b.png">
keep giving this problem

**Comment by swlkr** [comment]
Ah!

You need to change the team to your team (or you) and your signing cert as well under Signing & Capabilities

https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7

**Comment by swlkr** [comment]
I’m going to assume you got this working

**Comment by Alessandro-Stuccio** [comment]
Yes it works
